/* ---- User Dashboard Snapshots ----- */
create table public.user_dashboard_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  snapshot_date date not null,
  total_seconds_7d bigint not null default 0,
  active_days_7d integer not null default 0,
  consistency_percent integer not null default 0,
  current_streak integer not null default 0,
  best_streak integer not null default 0,
  peak_day date,
  peak_day_seconds bigint not null default 0,
  top_language text,
  top_language_percent numeric(5,2),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (user_id, snapshot_date),
  check (active_days_7d between 0 and 7),
  check (consistency_percent between 0 and 100),
  check (peak_day_seconds >= 0),
  check (
    top_language_percent is null
    or (top_language_percent >= 0 and top_language_percent <= 100)
  )
);

alter table public.user_dashboard_snapshots enable row level security;

create policy "Users can view their own dashboard snapshots"
on public.user_dashboard_snapshots
for select
using (auth.uid() = user_id);

create policy "Users can insert their own dashboard snapshots"
on public.user_dashboard_snapshots
for insert
with check (auth.uid() = user_id);

create policy "Users can update their own dashboard snapshots"
on public.user_dashboard_snapshots
for update
using (auth.uid() = user_id);
